### ISSUE TITLE
[11월 13일까지] Sprint 3 todolist

### ISSUE THREAD

**Issue by creeper00** [swsnu/swpp2020-team3#17]
현재 구현 상황:
- setting 완료
- views.py & models.py 구현 완료 (User model 제외)
- test.py ( post 부분만)

남은 구현:
- [x] 남은 부분 testing & bug fix
- [ ] User model 구현 (django 제공 User 에 extend 하는 방식)
- [ ] 여러 Error 상황에 대한 exception handling (ex: keyerror, authentication error, no exist error, etc)
- [ ] Login되야만 들어갈 수 있는 페이지 설정
- [ ] Recipe models에서 tag_list, category 둘중 하나 정하기

'# 담당 사람이 assign 하고 마치면  issue 닫기

**Comment by juimdpp** [comment]
저건 아직 못 했지만, signin, signup 부분 구현했음
