### ISSUE TITLE
CI - SonarCloud 연동 완료

### ISSUE THREAD

**Issue by kooyunmo** [swsnu/swpp2020-team3#26]
안녕하세요. CI-SonarCloud 연동 완료되었습니다. 팀 프로젝트를 진행하시면서 `.travis.yml` script는 팀 레포에 맞게 알아서 수정 바랍니다. 또한 수업 레포의 공지사항 참고하셔서 뱃지 설정 바랍니다.

https://travis-ci.org/github/swsnu/swpp2020-team3/jobs/741893700

**Comment by juimdpp** [comment]
감사합니다!!
